config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  root to: "welcome#index"

  get 'cohort', to: "cohort#index", as:"cohort"
  get 'cohort/:id/show', to: "cohort#show", as: "cohort_show"
  get 'cohort/:id/data', to: "cohort#data", as: "cohort_data"
  get 'cohort/:id/attendance', to: "cohort#attendance" , as: "cohort_att"
  get 'cohort/:id/homework/:hid/show', to: "cohort#homework", as: "cohort_hw"
  get 'student/:id/show', to: "student#show"
  get 'student/:id/comp', to: "student#comprehension"
  get 'student/:id/projects', to: "student#projects"
  post 'cohort/:id/attendance/:sid', to: "cohort#attendance_log"
  post 'cohort/new', to: "cohort#new"
  get 'cohort/:id/students/show', to: "cohort#studentsShow"
  post 'cohort/:id/student/new', to: "student#new"
  post 'student/:id/edit', to: "student#edit"
  get 'cohort/archived', to: "cohort#archived"
  post 'archive', to: "cohort#toggle_archive"
  post 'attendance', to: "cohort#attendance_log"
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :student
	belongs_to :cohort
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
	has_many :students
	has_many :teachers
	has_many :attendances
end

app/models/homework.rb
class Homework < ActiveRecord::Base
	belongs_to :student
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_and_belongs_to_many :projects
	has_many :homeworks
	has_many :attendances
	belongs_to :cohort
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	belongs_to :cohort
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def after_sign_in_path_for(resource)
	  cohort_path
	end
end

app/controllers/cohort_controller.rb
class CohortController < ApplicationController


def index
	@cohorts = Cohort.where({:archived => [false, nil]})
	p @cohorts
	@cohort = Cohort.new
	render :index
end

def new
      cohort_params = params.require(:cohort).permit(:name, :subject)
      cohort_params[:archived] = false
      p cohort_params
 	  cohort = Cohort.create(cohort_params)
      redirect_to "/cohort/#{cohort.id}/show"
    
end

def show
	@klass = Cohort.find(params[:id])
	@present = []
	@absent = []
	@students = 'x,'
	@cohort_id = @klass.id
	@cohort = @klass.students
	@averageComp = totalAverageComp(@cohort)
	@cohort.each do |stu|
		 @absent.push(stu.attendances.where({present: -1}).count)
		 @present.push(stu.attendances.where({present: 1}).count)
		 @students = @students + "#{stu.name},"
	end
	p @present
	p @students
	p @averageComp
	render :show
end

def data
    @cohort = Cohort.find(params[:id])
	render :data
end

def attendance
	klass = Cohort.find(params[:id])
	@cohort_id = klass.id
	@cohort = klass.students
	render :attendance
end

def homework
	klass = Cohort.find(params[:id])
	@cohort_id = klass
	@cohort = klass.students
	render :homework
end

def attendance_log
	# at this route params[:id] will be cohort_id 
	# params[:sid] will be student_id
	# will write a check for :sid == "all" to update all students
	p params[:present]
	@present = params[:present_students]
	@all = params[:all_students]

	@cohort = params[:cohort]
	@all.each do |student|
		att_params = {}
		att_params[:cohort_id] = @cohort
		att_params[:student_id] = student
		att_params[:date] = params[:date]
		if(@present != nil && @present.include?(student))
			att_params[:present] = 1
		else
			att_params[:present] = -1
		end	
		Attendance.create(att_params)
	end	
	redirect_to "/cohort/#{@cohort}/show"
end

def studentsShow
	@student = Student.new
	klass = Cohort.find(params[:id])
	@cohort_id = klass.id
	@cohort = klass.students
	render :studentsShow
end

def archived
	@cohorts = Cohort.where({:archived => true})
end

def toggle_archive
	p params[:id]
	cohort = Cohort.find(params[:id])
	p cohort
	if(cohort.archived != nil)
		cohort.archived = !cohort.archived
		p cohort
		cohort.save
	end	
	render :js => "location.reload();"
end

def averageComp(cohort, name)
	total = 0
	count = 0
	cohort.each do |stu|
		stu.homeworks.where(:name => name).each do |t|
			total += t.self_assessment
			count += 1
		end
	end
		if count == 0
			return "no submissions"
		else
		result = total / count
		result
	end
end

def totalAverageComp(cohort) 
	hwNames = []
	namesAndComp = []
	Homework.select("DISTINCT name").each do |t|
		hwNames.push(t.name)
	end
	hwNames.each do |t|
		result = averageComp(cohort, t)
		unless result == "no submissions"
			namesAndComp << t 
			namesAndComp << result
		end
	end
	namesAndComp
	end



end

app/controllers/student_controller.rb
class StudentController < ApplicationController

	def show
		@student = Student.find(params[:id])
		@projects = @student.projects
		render :show
	end

	def comprehension
		@student = Student.find(params[:id])
		render :comp
	end

	def projects
		render :projects
	end

	def new
		  student_params = params.require(:student).permit(:cohort_id, :github_username, :name)
	      p student_params
	 	  student = Student.create(student_params)
	      redirect_to "/student/#{student.id}/show"
	end

	def edit 
		student_params = params.require(:student).permit(:cohort_id, :github_username, :name)
		Student.update(params[:id], student_params )
		redirect_to "/student/#{params[:id]}/show"
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
 def controller?(*controller)
    controller.include?(params[:controller])
  end 

  def action?(*action)
    @current_action = action.include?(params[:action])
  end

  def current_page
  	current_page?(params[:action]) 
  end

end

app/helpers/cohort_helper.rb
module CohortHelper

end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cohort/archived.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container-fluid">
	<h1> Archived</h1>
	<ul> 
		<% @cohorts.each do |cohort| %>
		<li><h2><%=link_to "Cohort #{cohort.name}", cohort_show_path(cohort.id), :"data-no-turbolink" => true %> <%=  check_box_tag "#{cohort.id}"%></h2></li>
		<%end%>
	</ul>
	<div>
<!-- archive toggle button here -->
	</div>
   </div>

</body>
</htm

app/views/cohort/attendance.html.erb
<html>
<head>
	<title></title>

</head>
<body>
 <div class="container-fluid">
<h1>cohort attendance page</h1>
<%=form_tag '/attendance' do %>
 <input type="date" id="date" data-format="DD-MM-YYYY" data-template="D MMM YYYY" name="date" placeholder="12-01-2015">
<ul>

	<% @cohort.each do |student|%>
		<li>
			<div class="row">
				<div class="col-md-4">
					<h3><%= link_to "#{student.name}", "/student/#{student.id}/show"%></h3> 
				</div>
				<div class="col-md-4">
					<%=check_box_tag 'present_students[]', student.id %>					
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</li>
		<%= hidden_field_tag 'all_students[]', student.id %>
	<% end %>
	<%= submit_tag "submit", class: "btn btn-info"%>
	<%= hidden_field_tag 'cohort', @cohort_id %>
<% end %>
<button type="button" class="btn btn-success" id="allHere">All Here</button>

</ul>
</div>
</body>
</html>

app/views/cohort/data.html.erb
<html>
<head>
	<title></title>
</head>
<body>


	<div class="container-fluid">
<h1>Cohort Data Page</h1>
<hr>
<h2> Class Attendance </h2>
<div class="chart">
	<div id="chart" class="c3"></div>
</div>
<h2> Average Comprehension </h2>
<div class="compChart">
	<div id="compChart" class="c3"></div>
</div>
<style>
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  position: relative;
  width: 960px;
}

.axis text {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.bar {
  fill: steelblue;
  fill-opacity: .9;
}

.x.axis path {
  display: none;
}

label {
  position: absolute;
  top: 10px;
  right: 10px;
}

</style>
<script>
var chart = c3.generate({
    bindto: '#chart',
    data: {
    	onclick: function(d, element) {
    		window.location= "/student/1/show"
    	},
        columns: [
            window.presentData,
            window.absentData
        ],
        type: 'bar'
    },
    bar: {
        width: {
            ratio: 0.5 // this makes bar width 50% of length between ticks
        }
        // or
        //width: 100 // this makes bar width 100px
    }
});

setTimeout(function () {
    chart.load({
        columns: [
            ['data3', 130, -150, 200, 300, -200, 100]
        ]
    });
}, 1000);

var mychart = c3.generate({
	bindto: '#compChart',
    data: {
    	//hardcoded redirect to test, will have to make dynamic
    	onclick: function(d, element) {
    		window.location= "/cohort/1/homework/1/show"
    	},
        xs: {
            'data1': 'x1',
            'data2': 'x2',
        },
        columns: [
            ['x1', 10, 30, 45, 50, 70, 100],
            ['x2', 30, 50, 75, 100, 120],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 20, 180, 240, 100, 190]
        ]
    }
});
</script>

</div>
</body>
</html>

app/views/cohort/homework.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<h1>cohort Homework page</h1>
<ul>
<% @cohort.each do |student|%>
<li>
	<div class="row">
		<div class="col-md-4">
			<%= student.name%> 
		</div>
		<div class="col-md-4">
			<!-- mock up button that will change color. -->
			<p> 3/5 reported comprehension</p>
		</div>
		<div class="col-md-4">
			<p> Rails is the worst!!! </p>
		</div>
	</div>
</li>
<% end %>
</ul>
</body>
</html>

app/views/cohort/index.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container-fluid">
	<h1> Available Cohorts </h1>
	<ul> 
		<% @cohorts.each do |cohort| %>
		<li><h2><%=link_to "Cohort #{cohort.name} - #{cohort.subject}", cohort_show_path(cohort.id), :"data-no-turbolink" => true %> <%=  check_box_tag "#{cohort.id}"%></h2></li>
		<%end%>
	</ul>
	<div>
		<%= form_for @cohort, url: "/cohort/new" do  |f| %>
						<%= f.text_field :name, :placeholder => "Cohort Number" %><br>
						<%= f.select :subject, [["UXDI", "UXDI"], ["WDI", "WDI"], ["PMI", "PMI"], ["FEWD", "FEWD"], ["BEWD", "BEWD"]]%><br>
						<%= f.submit "Add cohort" %>
					<% end %>
	</div>
	<div class="pull-right">
		<button><%=link_to "Archived", "/cohort/archived"%></button>
	</div>
   </div>

</body>
</html>

app/views/cohort/show.html.erb
<html>
<head>
	<title></title>
	<script type="text/javascript"></script>
</head>
<body>
	<%= javascript_tag do %>
	window.averageComp = JSON.parse('<%= @averageComp %>'.replace(/&quot;/g,'"'));
  window.presentData = JSON.parse('<%=  @present %>');
  window.absentData = JSON.parse('<%=  @absent %>');
  window.students = '<%= @students %>';

<% end %>
<div class="container-fluid">
	<h1><%=@klass.subject%> <%=@klass.name%></h1>
	<hr>
	<h2> Class Attendance </h2>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4" style="text-align: center;">
			<button class="btn"><%= link_to "Students", "/cohort/#{@klass.id}/students/show"%></button>
			<button class="btn"><%= link_to "Attendance", "/cohort/#{@klass.id}/attendance"%></button>
			<button class="btn"><%= link_to "Projects", "/cohort/#{@klass.id}/projects"%></button>
		</div>
	</div>
	<hr>
	<div class="chart">
		<div id="chart" class="c3"></div>
	</div>
	<h2> Average Comprehension </h2>
	<div class="compChart">
		<div id="compChart" class="c3"></div>
	</div>
	<hr>

</div>
</body>
</html>

app/views/cohort/studentsShow.html.erb
<h1>cohort/Student show page</h1>
<ul>
<% @cohort.each do |student|%>
<li>
	<div class="row">
		<div class="col-md-4">

			<h3><%= link_to "#{student.name}", "/student/#{student.id}/show"%></h3> 
		</div>
		<div class="col-md-4">
			<!-- mock up button that will change color. -->
			<button type="button" class="btn btn-success">Good
			</button>
		</div>
		<div class="col-md-4">
			Flag message in here
		</div>
	</div>
</li>
<% end %>
</ul>
<div>
		<%= form_for @student, url: "/cohort/#{@cohort_id}/student/new" do  |f| %>
						<%= f.text_field :name, :placeholder => "name" %><br>
						<%= f.text_field :github_username, :placeholder => "GitHub Name" %><br>
						<%= f.hidden_field :cohort_id, :value => @cohort_id  %>
						<%= f.submit "Add New Student" %>
					<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LittleLms</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  	<link href="/assets/c3.min.css" rel="stylesheet" type="text/css">
 	<script src="//d3js.org/d3.v3.min.js"></script>
<!-- <script src="/assets/c3.min.js"></script>
<script src="/assets/cohort.js"></script> -->
</head>
<body>

<%= render "partials/nav" unless @disable_nav %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if teacher_signed_in? %>
  Logged in as <strong><%= current_teacher.email %></strong>.
  <%= link_to 'Edit profile', edit_teacher_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_teacher_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_teacher_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_teacher_session_path, :class => 'navbar-link'  %>
<% end %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/student/comp.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<div class="container-fluid">
<h1>Student Comprehension Page</h1>

<h2> Average Comprehension </h2>
<div class="studentCompChart">
	<div id="studentCompChart" class="c3"></div>
</div>
</div>
<script>
var mychart = c3.generate({
	bindto: '#studentCompChart',
    data: {
        xs: {
            'data1': 'x1',
            'data2': 'x2',
        },
        columns: [
            ['x1', 10, 30, 45, 50, 70, 100],
            ['x2', 30, 50, 75, 100, 120],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 20, 180, 240, 100, 190]
        ]
    }
});
</script>
</body>

</html>

app/views/student/projects.html.erb
<html>
<head>
	<title></title>
</head>
<body>
Student Projects Page
</body>
</html>

app/views/student/show.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<div class="container-fluid">
<h1><%= @student.name %> <%=@student.id%></h1>
<hr>
	<li><h3><%= link_to "GitHub",  "http://github.com/#{@student.github_username}" %></h3></li>
<div>
	<%= form_for @student, url: "/student/#{@student.id}/edit", :method => "post" do  |f| %>
						<%= f.label :name %>
						<%= f.text_field :name, :placeholder => "name" %><br>
						<%= f.label :github_username, 'Github Username' %>
						<%= f.text_field :github_username, :placeholder => "GitHub Name" %><br>
						<%= f.label :cohort_id %>
						<%= f.number_field :cohort_id, :placeholder =>  @student.cohort_id  %>
						<%= f.submit "Update Student" %>
					<% end %>
<div>
</div>

</body>
</html>